[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Static HTML site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
